version: "3"
services:
  mylar:
    build: .
    image: ajslater/mylar3
    container_name: mylar
    ports:
      - "8090:8090"
    volumes:
      - ./mylar/comics:/comics
      - ./mylar/config:/config
      - ./mylar/data:/data
      - ./mylar/downloads:/downloads
    env_file:
      - env
