version: 2.1
executors:
    docker-publisher:
        machine: true
parameters:
  image_archive:
    type: string
    default: "image.tar"

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Build Mylar
          command: ./build.sh
      - run:
          name: Archive Docker image
          command: ./ci/archive-image.sh ./<< parameters.image_archive >>
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.image_archive >>
  deploy:
    executor: docker-publisher
    parameters:
      tmp_workspace:
        type: string
        default: "/tmp/workspace"
    steps:
      - attach_workspace:
          at: << parameters.tmp_workspace >>
      - run:
          name: Load archive Docker image
          command: docker load -i "<< parameters.tmp_workspace >>/<< parameters.image_archive >>"
      - run:
          name: Publish Docker Image to Docker Hub
          command: ./tag-and-push.sh

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
                only: master
